# source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '16.0'

# # Resolve react_native_pods.rb path dynamically
# react_native_pods_path = Pod::Executable.execute_command('node', ['-p', 'require.resolve("react-native/scripts/react_native_pods.rb")']).strip
# require react_native_pods_path

# # Prepare React Native environment
# prepare_react_native_project!

# # Use dynamic frameworks if specified via environment variable
# linkage = ENV['USE_FRAMEWORKS']
# if linkage
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# # Define project
# project 'SwiftRNApp.xcodeproj'

# target 'SwiftRNApp' do
#   # This will detect and configure native modules in your React Native app
#   config = use_native_modules!

#   # React Native dependencies
#   use_react_native!(
#     :path => config[:reactNativePath],
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   # post_install do |installer|
#   #   # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#   #   react_native_post_install(
#   #     installer,
#   #     config[:reactNativePath],
#   #     :mac_catalyst_enabled => false,
#   #     # :ccache_enabled => true
#   #   )
#   # end
# end

# require_relative '../node_modules/react-native/scripts/react_native_pods'

# source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '16.0'

# prepare_react_native_project!
 
# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# target 'SwiftRNApp' do
#   # React Native core pods
#   pod 'React-Core', :path => '../node_modules/react-native'
#   pod 'React-Core/DevSupport', :path => '../node_modules/react-native'
#   pod 'React-RCTText', :path => '../node_modules/react-native'
#   pod 'React-RCTImage', :path => '../node_modules/react-native'
#   pod 'React-RCTNetwork', :path => '../node_modules/react-native'
#   pod 'React-RCTLinking', :path => '../node_modules/react-native'
#   pod 'React-RCTSettings', :path => '../node_modules/react-native'
#   pod 'React-RCTAnimation', :path => '../node_modules/react-native'
#   # pod 'React-RCTActionSheet', :path => '../node_modules/react-native'
#   # pod 'React-RCTBlob', :path => '../node_modules/react-native'
#   pod 'React-RCTWebSocket', :path => '../node_modules/react-native'
  
#   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon'

#   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
#   # # 3rd party dependencies
#   # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#   # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
# end


require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SwiftRNApp' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :app_path => '../',
    :hermes_enabled => true,  # or false, depending on your RN config
    :fabric_enabled => false  # unless you're using the new Fabric renderer
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      '../node_modules/react-native'
    )
  end
end

